version: '3'
services:
  web:
    build: site
    volumes:
      - ./www:/var/www/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - composer
    environment:
      - JWT_SECRET_KEY=o58BDHpCdnI4Y6iYtmk9RLJ5IVbB8svfsPw09kjiupAMrab0vO4JdXmZunG3kSat
      - DOMAIN=34.136.248
    ports:
      - "8080:80"

  composer:
    image: composer:latest
    volumes:
      - ./www:/var/www/
    working_dir: /var/www/

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: esgi
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: esgipwd
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www
    depends_on:
      - web
      - pgadmin
  
  sass:
    image: node:latest
    volumes:
      - ./www:/var/www/
    working_dir: /var/www/
    command: sh -c "npm install -g sass && sass --watch /var/www/Public/Asset/scss:/var/www/Public/Asset/scss"

  # sass:
  #   image: larryprice/sass
  #   volumes:
  #     - ./:/src
    
volumes:
  mariadb_data:
