version: '3'
services:
  web:
    build: site
    ports :
      - "80:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: my_database
      POSTGRES_USER: group12
      POSTGRES_PASSWORD: g12
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini



  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: group12
      POSTGRES_PASSWORD: g12




  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: postgres
    ports:
      - "8080:80"
    depends_on:
      - postgres
