/:
  Controller: "Main"
  Action: "home"


/login:
  Controller: "Security"
  Action: "login"

/dashboard:
  Controller: "Security"
  Action: "dashboard"

/register:
  Controller: "Security"
  Action: "register"

/logout:
  Controller: "Security"
  Action: "logout"


/ajout-utilisateur:
  Controller: "User"
  Action: "add"

/del-utilisateur:
  Controller: "User"
  Action: "delete"

/show-utilisateur:
  Controller: "User"
  Action: "show"

/list-utilisateurs:
  Controller: "User"
  Action: "list"

/maj-utilisateurs:
  Controller: "User"
  Action: "edit"
