/:
  IsAdmin: false
  Islog: false
  Controller: "Main"
  Action: "home"

/dashboard/user:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "user"

/dashboard/invite-user:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "invite"

/login:
  IsAdmin: false
  Islog: true
  Controller: "Security"
  Action: "login"

/validate:
  IsAdmin: false
  Islog: false
  Controller: "Security"
  Action: "validate"

/reset_password:
  IsAdmin: false
  Islog: false
  Controller: "Security"
  Action: "reset_password"

/register:
  Islog: true
  IsAdmin: false
  Controller: "Security"
  Action: "register"

/logout:
  Islog: true
  IsAdmin: true
  Controller: "Security"
  Action: "logout"


/ajout-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "add"

/del-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "delete"

/show-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "show"

/list-utilisateurs:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "list"

/maj-utilisateurs:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "edit"
