/:
  Islog: false
  IsAdmin: false
  Controller: "Main"
  Action: "home"


/login:
  IsAdmin: false
  Islog: true
  Controller: "Security"
  Action: "login"

/register:
  Islog: true
  IsAdmin: false
  Controller: "Security"
  Action: "register"

/logout:
  Islog: true
  IsAdmin: true
  Controller: "Security"
  Action: "logout"


/ajout-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "add"

/del-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "delete"

/show-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "show"

/list-utilisateurs:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "list"

/maj-utilisateurs:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "edit"
