/:
  IsAdmin: false
  Islog: false
  Controller: "Main"
  Action: "home"

/front/home:
  IsAdmin: false
  Islog: false
  Controller: "Front"
  Action: "home"

/front/about:
  IsAdmin: false
  Islog: false
  Controller: "Front"
  Action: "about"

/front/contact:
  IsAdmin: false
  Islog: false
  Controller: "Front"
  Action: "contact"

/front/forum:
  IsAdmin: false
  Islog: false
  Controller: "Front"
  Action: "forum"

/front/actu:
  IsAdmin: false
  Islog: false
  Controller: "Front"
  Action: "actu"

/dashboard:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "home"

/create-club:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "create_club"

/dashboard/user:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "user"

/dashboard/manage-pages/delete-page:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "delete_page"

/dashboard/profil:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "profil"

/dashboard/article:
  IsAdmin: false
  Islog: false
  Controller: "Articles"
  Action: "article"

/dashboard/article/create-article:
  IsAdmin: false
  Islog: false
  Controller: "Articles"
  Action: "create_article"

/dashboard/article/update-article:
  IsAdmin: false
  Islog: false
  Controller: "Articles"
  Action: "update_article"

/dashboard/invite-user:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "invite"

/dashboard/manages-pages:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "allpages"

/dashboard/manage-pages/create-page:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "create_page"

/dashboard/manage-pages/build-page:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "build_page"

/dashboard/manage-pages/website_manager:
  IsAdmin: false
  Islog: false
  Controller: "Dashboard"
  Action: "website_manager"

/login:
  IsAdmin: false
  Islog: true
  Controller: "Security"
  Action: "login"

/validate:
  IsAdmin: false
  Islog: false
  Controller: "Security"
  Action: "validate"

/reset_password:
  IsAdmin: false
  Islog: false
  Controller: "Security"
  Action: "reset_password"

/register:
  Islog: true
  IsAdmin: false
  Controller: "Security"
  Action: "register"

/logout:
  Islog: true
  IsAdmin: true
  Controller: "Security"
  Action: "logout"


/ajout-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "add"

/del-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "delete"

/show-utilisateur:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "show"

/list-utilisateurs:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "list"

/maj-utilisateurs:
  Islog: true
  IsAdmin: true
  Controller: "User"
  Action: "edit"
